#                                                                                                             
#  88888888ba   88888888ba   88888888888  I8,        8        ,8I  88888888888  88  88           88888888888  
#  88      "8b  88      "8b  88           `8b       d8b       d8'  88           88  88           88           
#  88      ,8P  88      ,8P  88            "8,     ,8"8,     ,8"   88           88  88           88           
#  88aaaaaa8P'  88aaaaaa8P'  88aaaaa        Y8     8P Y8     8P    88aaaaa      88  88           88aaaaa      
#  88""""""8b,  88""""88'    88"""""        `8b   d8' `8b   d8'    88"""""      88  88           88"""""      
#  88      `8b  88    `8b    88              `8a a8'   `8a a8'     88           88  88           88           
#  88      a8P  88     `8b   88               `8a8'     `8a8'      88           88  88           88           
#  88888888P"   88      `8b  88888888888       `8'       `8'       88           88  88888888888  88888888888  
#                                                                                                             

# Taps
tap 'homebrew/cask-fonts'
tap 'mongodb/brew'
tap 'localsend/localsend'

# Dev
brew 'python3'
brew 'node'
brew 'mongodb-community'
brew 'rust'

# Tools
brew 'mas'
brew 'yt-dlp'
brew 'ffmpeg'

# Customization
brew 'neofetch'

# Font Casks
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-roboto'
cask 'font-inter'
cask 'font-lato'
cask 'font-raleway'
cask 'font-rubik'

# App Casks
cask 'arc'
cask 'google-chrome'
cask 'tor-browser'
cask 'thunderbird'
cask 'microsoft-office'
cask 'spotify'
cask 'notion'
cask 'vlc'
cask 'teamviewer'
cask 'zoom'
cask 'rekordbox'
cask 'ultimaker-cura'
cask 'obs'
cask 'blender'
cask 'localsend'

# Tool Casks
cask 'appcleaner'
cask 'the-unarchiver'
cask 'bitwarden'
cask 'openinterminal'
cask 'nightfall'
cask 'moom'
cask 'tailscale'
cask 'itsycal'
cask 'aldente'
cask 'balenaetcher'
cask 'raycast'
cask 'rustdesk'

# Quicklook Casks
cask 'quicklook-json'
cask 'qlmarkdown'

# Dev Casks
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'visual-studio-code'
cask 'docker'
cask 'postman'
cask 'cyberduck'
cask 'mongodb-compass'
cask 'termius'
cask 'openscad'
cask 'unity'
cask 'scrcpy'

# Social Casks
cask 'signal'
cask 'whatsapp'
cask 'discord'
cask 'telegram'
cask 'mattermost'

# Gaming Casks
cask 'parsec'
cask 'minecraft'
cask 'steam'
cask 'battle-net'
cask 'epic-games'

# Mac App Store Apps
mas 'AusweisApp', id: 948660805
mas 'Unsplash Wallpapers', id: 1284863847
mas 'Amphetamine', id: 937984704
mas 'Notability', id: 360593530
mas 'ColorSlurp', id: 1287239339
mas 'Plash'
